v_name = input("What is your name?\n")
v_age = int(input("How old are you?\n"))
v_decades = int(v_age / 10)
v_months = int(v_age % 10)
print (f"Hello Andy!\n\nYou are {v_decades} decads \n and {v_months} years old.")